site_name: kubenav
site_description: kubenav is the navigator for your Kubernetes clusters right in your pocket.
repo_name: kubenav/kubenav
repo_url: https://github.com/kubenav/kubenav
edit_uri: https://github.com/kubenav/docs/edit/master/docs/
copyright: Rico Berger

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png
  include_search_page: false
  search_index_only: true

nav:
  - Home: index.md
  - Screenshots: screenshots.md
  - Mobile:
      - Getting started: mobile/getting-started.md
      - Cluster Configuration:
          - Google: mobile/google.md
          - Amazon Web Services: mobile/amazon-web-services.md
          - Microsoft Azure: mobile/microsoft-azure.md
          - DigitalOcean: mobile/digital-ocean.md
          - OIDC: mobile/oidc.md
          - Kubeconfig: mobile/kubeconfig.md
          - Manual: mobile/manual.md
      - Settings: mobile/settings.md
  - Desktop:
      - Getting started: desktop/getting-started.md
      - Configuration: desktop/configuration.md
      - Settings: desktop/settings.md
      - Command-line flags: desktop/command-line-flags.md
  - Web:
      - Getting started: web/getting-started.md
      - Kustomize: web/kustomize.md
      - Helm: web/helm.md
      - Configure access to multiple clusters: web/multi-cluster-access.md
      - Settings: web/settings.md
      - Command-line flags: web/command-line-flags.md
  - Plugins:
      - Helm: plugins/helm.md
      - Prometheus: plugins/prometheus.md
  - Contributing:
      - Getting started: contributing/getting-started.md
      - Development: contributing/development.md
      - Release: contributing/release.md

plugins:
  - search

extra:
  social:
    - icon: material/web
      link: https://kubenav.io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubenav
    - icon: fontawesome/brands/app-store-ios
      link: https://apps.apple.com/us/app/kubenav/id1494512160
    - icon: fontawesome/brands/google-play
      link: https://play.google.com/store/apps/details?id=io.kubenav.kubenav
    - icon: fontawesome/solid/desktop
      link: https://github.com/kubenav/kubenav/releases
    - icon: material/kubernetes
      link: https://github.com/kubenav/deploy
    - icon: fontawesome/brands/github
      link: https://github.com/kubenav/kubenav
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kubenav/kubenav

extra_css:
  - stylesheets/extra.css
